version: '3.7'

services:
  app:
    container_name: webshell
    build: .
    # image: registry.oidatiftla.de/webshell
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - 80:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s
